export type Condition = "Brand New" | "Ex-UK / Refurbished" | "Used";

export type Product = {
  slug: string;
  name: string;
  brand: string;
  category: CategorySlug;
  price: number;
  oldPrice?: number;
  sku: string;
  condition: Condition;
  inStock: boolean;
  rating: number;
  reviews: number;
  tags: Array<"hot-deal" | "new-arrival" | "best-seller" | "featured" | "clearance">;
  specs: Record<string, string>;
  features: string[];
  description: string;
  warranty: string;
};

export type CategorySlug =
  | "computers"
  | "accessories"
  | "networking"
  | "printers-scanners"
  | "cctv-security"
  | "gaming"
  | "pos-systems"
  | "apple"
  | "software";

export type Category = {
  slug: CategorySlug;
  name: string;
  short: string;
  description: string;
  icon: string;
};

export const categories: Category[] = [
  {
    slug: "computers",
    name: "Computers & Laptops",
    short: "Computers",
    description: "Laptops, desktops, workstations and complete computer systems.",
    icon: "Laptop",
  },
  {
    slug: "accessories",
    name: "Accessories",
    short: "Accessories",
    description: "Keyboards, mice, bags, cables, chargers, adapters and storage.",
    icon: "Mouse",
  },
  {
    slug: "printers-scanners",
    name: "Printers & Scanners",
    short: "Printers",
    description: "Home, office and business printing solutions.",
    icon: "Printer",
  },
  {
    slug: "networking",
    name: "Networking",
    short: "Networking",
    description: "Routers, switches, access points, cables and networking accessories.",
    icon: "Router",
  },
  {
    slug: "cctv-security",
    name: "CCTV & Security",
    short: "CCTV",
    description: "Cameras, DVR/NVR systems, storage and security accessories.",
    icon: "Cctv",
  },
  {
    slug: "gaming",
    name: "Gaming",
    short: "Gaming",
    description: "Gaming PCs, monitors, accessories and peripherals.",
    icon: "Gamepad2",
  },
  {
    slug: "pos-systems",
    name: "POS Systems",
    short: "POS",
    description: "Point-of-sale hardware and business technology.",
    icon: "ScanLine",
  },
  {
    slug: "apple",
    name: "Apple Products",
    short: "Apple",
    description: "Apple computers, accessories and related products.",
    icon: "Apple",
  },
  {
    slug: "software",
    name: "Software",
    short: "Software",
    description: "Operating systems, productivity software and business solutions.",
    icon: "AppWindow",
  },
];

export function getCategory(slug: string) {
  return categories.find((c) => c.slug === slug);
}

const p = (product: Product) => product;

export const products: Product[] = [
  p({
    slug: "hp-elitebook-840-g6-core-i5",
    name: "HP EliteBook 840 G6 Core i5 8th Gen",
    brand: "HP",
    category: "computers",
    price: 42500,
    oldPrice: 49000,
    sku: "AGK-CMP-001",
    condition: "Ex-UK / Refurbished",
    inStock: true,
    rating: 4.6,
    reviews: 18,
    tags: ["hot-deal", "best-seller", "featured"],
    specs: {
      Processor: "Intel Core i5 8th Gen",
      RAM: "8GB DDR4",
      Storage: "256GB SSD",
      "Screen size": "14 inch",
      GPU: "Intel UHD Graphics",
      "Operating system": "Windows 11 Pro",
    },
    features: [
      "Slim aluminium business chassis",
      "Backlit keyboard and fingerprint reader",
      "Full-day battery for work on the move",
    ],
    description:
      "A reliable business ultrabook for professionals, students and office use. Tested, cleaned and ready to work out of the box.",
    warranty: "3 months limited warranty",
  }),
  p({
    slug: "dell-latitude-5420-core-i7",
    name: "Dell Latitude 5420 Core i7 11th Gen",
    brand: "Dell",
    category: "computers",
    price: 78500,
    oldPrice: 86000,
    sku: "AGK-CMP-002",
    condition: "Ex-UK / Refurbished",
    inStock: true,
    rating: 4.7,
    reviews: 11,
    tags: ["featured", "best-seller"],
    specs: {
      Processor: "Intel Core i7 11th Gen",
      RAM: "16GB DDR4",
      Storage: "512GB SSD",
      "Screen size": "14 inch",
      GPU: "Intel Iris Xe",
      "Operating system": "Windows 11 Pro",
    },
    features: ["Fast 11th Gen performance", "16GB RAM for heavy multitasking", "Business-grade build quality"],
    description:
      "A powerful business laptop built for demanding workloads, from spreadsheets and design work to development.",
    warranty: "3 months limited warranty",
  }),
  p({
    slug: "lenovo-thinkpad-t480-core-i5",
    name: "Lenovo ThinkPad T480 Core i5 8th Gen",
    brand: "Lenovo",
    category: "computers",
    price: 38900,
    sku: "AGK-CMP-003",
    condition: "Ex-UK / Refurbished",
    inStock: true,
    rating: 4.5,
    reviews: 24,
    tags: ["best-seller"],
    specs: {
      Processor: "Intel Core i5 8th Gen",
      RAM: "8GB DDR4",
      Storage: "256GB SSD",
      "Screen size": "14 inch",
      GPU: "Intel UHD Graphics",
      "Operating system": "Windows 11 Pro",
    },
    features: ["Legendary ThinkPad keyboard", "Dual battery design", "Durable, repair-friendly build"],
    description: "A dependable everyday laptop for students and professionals who need something that lasts.",
    warranty: "3 months limited warranty",
  }),
  p({
    slug: "hp-prodesk-600-g4-desktop",
    name: "HP ProDesk 600 G4 Desktop Set",
    brand: "HP",
    category: "computers",
    price: 34500,
    oldPrice: 39500,
    sku: "AGK-CMP-004",
    condition: "Ex-UK / Refurbished",
    inStock: true,
    rating: 4.4,
    reviews: 9,
    tags: ["hot-deal"],
    specs: {
      Processor: "Intel Core i5 8th Gen",
      RAM: "8GB DDR4",
      Storage: "500GB HDD",
      "Screen size": "19 inch monitor included",
      "Operating system": "Windows 11 Pro",
    },
    features: ["Complete set with monitor, keyboard and mouse", "Ideal for offices and cyber cafés", "Compact desktop tower"],
    description: "A complete desktop workstation for office desks, front offices, schools and home study rooms.",
    warranty: "3 months limited warranty",
  }),
  p({
    slug: "asus-vivobook-15-ryzen-5",
    name: "ASUS VivoBook 15 Ryzen 5 (New)",
    brand: "ASUS",
    category: "computers",
    price: 64900,
    sku: "AGK-CMP-005",
    condition: "Brand New",
    inStock: true,
    rating: 4.5,
    reviews: 6,
    tags: ["new-arrival"],
    specs: {
      Processor: "AMD Ryzen 5",
      RAM: "8GB DDR4",
      Storage: "512GB SSD",
      "Screen size": "15.6 inch FHD",
      GPU: "AMD Radeon Graphics",
      "Operating system": "Windows 11 Home",
    },
    features: ["Brand new, sealed unit", "Large FHD display", "Lightweight everyday laptop"],
    description: "A brand-new all-round laptop for study, work and home use with a bright 15.6-inch display.",
    warranty: "12 months manufacturer warranty",
  }),
  p({
    slug: "logitech-mk270-wireless-combo",
    name: "Logitech MK270 Wireless Keyboard & Mouse Combo",
    brand: "Logitech",
    category: "accessories",
    price: 3900,
    oldPrice: 4500,
    sku: "AGK-ACC-001",
    condition: "Brand New",
    inStock: true,
    rating: 4.6,
    reviews: 31,
    tags: ["hot-deal", "best-seller"],
    specs: { Type: "Wireless combo", Connectivity: "2.4GHz USB receiver", Battery: "Up to 24 months (keyboard)" },
    features: ["Plug-and-play wireless", "Spill-resistant keyboard", "Long battery life"],
    description: "A reliable wireless keyboard and mouse set for office desks and home workstations.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "sandisk-ultra-128gb-flash-drive",
    name: "SanDisk Ultra 128GB USB 3.0 Flash Drive",
    brand: "SanDisk",
    category: "accessories",
    price: 1850,
    sku: "AGK-ACC-002",
    condition: "Brand New",
    inStock: true,
    rating: 4.8,
    reviews: 52,
    tags: ["best-seller"],
    specs: { Capacity: "128GB", Interface: "USB 3.0", "Read speed": "Up to 130MB/s" },
    features: ["Fast file transfers", "Compact and durable", "Great for students"],
    description: "High-speed USB flash storage for documents, projects, media and backups.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "wd-1tb-external-hard-drive",
    name: "WD Elements 1TB Portable External Hard Drive",
    brand: "Western Digital",
    category: "accessories",
    price: 8900,
    oldPrice: 9800,
    sku: "AGK-ACC-003",
    condition: "Brand New",
    inStock: true,
    rating: 4.7,
    reviews: 27,
    tags: ["featured"],
    specs: { Capacity: "1TB", Interface: "USB 3.0", Format: "Windows / macOS compatible" },
    features: ["Plug-and-play backup storage", "Portable and lightweight", "Ideal for CCTV and media archives"],
    description: "Portable external storage for backups, media libraries and business documents.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "laptop-backpack-156",
    name: "Business Laptop Backpack 15.6\"",
    brand: "AGIKA Essentials",
    category: "accessories",
    price: 2500,
    sku: "AGK-ACC-004",
    condition: "Brand New",
    inStock: true,
    rating: 4.3,
    reviews: 14,
    tags: ["new-arrival"],
    specs: { Fits: "Up to 15.6 inch laptops", Material: "Water-resistant polyester", Extras: "USB charging port" },
    features: ["Padded laptop compartment", "Water-resistant finish", "Comfortable shoulder straps"],
    description: "A smart, protective backpack for daily commuting with your laptop and accessories.",
    warranty: "3 months warranty",
  }),
  p({
    slug: "hp-laptop-charger-65w",
    name: "HP 65W Laptop Charger (Blue Pin)",
    brand: "HP",
    category: "accessories",
    price: 2200,
    sku: "AGK-ACC-005",
    condition: "Brand New",
    inStock: true,
    rating: 4.4,
    reviews: 20,
    tags: [],
    specs: { Output: "65W", Connector: "4.5mm blue pin", Compatibility: "HP EliteBook / ProBook / Pavilion" },
    features: ["Genuine replacement charger", "Stable power delivery", "Compatible with most HP business laptops"],
    description: "A dependable replacement charger for HP laptops with the standard blue-pin connector.",
    warranty: "3 months warranty",
  }),
  p({
    slug: "canon-lbp6030-laser-printer",
    name: "Canon i-SENSYS LBP6030 Mono Laser Printer",
    brand: "Canon",
    category: "printers-scanners",
    price: 21500,
    oldPrice: 23500,
    sku: "AGK-PRN-001",
    condition: "Brand New",
    inStock: true,
    rating: 4.5,
    reviews: 12,
    tags: ["hot-deal", "best-seller"],
    specs: { Type: "Mono laser", "Print speed": "18 ppm", Connectivity: "USB 2.0" },
    features: ["Compact desktop footprint", "Low running cost", "Quick first-print out"],
    description: "A compact mono laser printer for small offices, shops and home use.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "epson-l3210-ecotank",
    name: "Epson EcoTank L3210 All-in-One Printer",
    brand: "Epson",
    category: "printers-scanners",
    price: 27900,
    sku: "AGK-PRN-002",
    condition: "Brand New",
    inStock: true,
    rating: 4.7,
    reviews: 22,
    tags: ["featured", "best-seller"],
    specs: { Type: "Ink tank all-in-one", Functions: "Print, scan, copy", Connectivity: "USB" },
    features: ["Very low cost per page", "Print, scan and copy in one unit", "Refillable ink tanks"],
    description: "The popular EcoTank all-in-one for offices, schools and businesses that print in volume.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "hp-scanjet-2600-scanner",
    name: "HP ScanJet Pro 2600 Flatbed Scanner",
    brand: "HP",
    category: "printers-scanners",
    price: 24500,
    sku: "AGK-PRN-003",
    condition: "Brand New",
    inStock: false,
    rating: 4.4,
    reviews: 5,
    tags: [],
    specs: { Type: "Flatbed scanner", Resolution: "1200 dpi", Connectivity: "USB" },
    features: ["Sharp document scanning", "Simple one-touch buttons", "Compact desktop design"],
    description: "A dependable flatbed scanner for offices digitising documents and records.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "tp-link-archer-c6-router",
    name: "TP-Link Archer C6 AC1200 Dual Band Router",
    brand: "TP-Link",
    category: "networking",
    price: 5900,
    oldPrice: 6800,
    sku: "AGK-NET-001",
    condition: "Brand New",
    inStock: true,
    rating: 4.6,
    reviews: 38,
    tags: ["hot-deal", "best-seller"],
    specs: { Speed: "AC1200 dual band", Ports: "4x Gigabit LAN", Antennas: "4 external" },
    features: ["Strong home and office Wi-Fi", "Easy setup via app", "Gigabit wired ports"],
    description: "A dependable dual-band router that covers homes, shops and small offices.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "tp-link-8-port-gigabit-switch",
    name: "TP-Link 8-Port Gigabit Desktop Switch",
    brand: "TP-Link",
    category: "networking",
    price: 3400,
    sku: "AGK-NET-002",
    condition: "Brand New",
    inStock: true,
    rating: 4.7,
    reviews: 16,
    tags: [],
    specs: { Ports: "8x Gigabit", Housing: "Steel case", Setup: "Plug and play" },
    features: ["Expand your office network", "Silent fanless operation", "Durable metal casing"],
    description: "A simple gigabit switch to add more wired connections to your office network.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "cat6-network-cable-305m",
    name: "CAT6 Network Cable Roll — 305 Metres",
    brand: "D-Link",
    category: "networking",
    price: 12500,
    sku: "AGK-NET-003",
    condition: "Brand New",
    inStock: true,
    rating: 4.5,
    reviews: 8,
    tags: ["featured"],
    specs: { Length: "305m box", Category: "CAT6 UTP", Use: "Indoor structured cabling" },
    features: ["Full box for structured cabling", "Supports gigabit speeds", "Ideal for office and CCTV installs"],
    description: "A full box of CAT6 cable for office networking and CCTV cabling projects.",
    warranty: "Manufacturer standard",
  }),
  p({
    slug: "ubiquiti-unifi-access-point",
    name: "Ubiquiti UniFi AC Lite Access Point",
    brand: "Ubiquiti",
    category: "networking",
    price: 16900,
    sku: "AGK-NET-004",
    condition: "Brand New",
    inStock: true,
    rating: 4.8,
    reviews: 7,
    tags: ["new-arrival"],
    specs: { Speed: "AC1200", Power: "PoE", Coverage: "Up to 122m" },
    features: ["Business-grade Wi-Fi coverage", "Central UniFi management", "Ceiling or wall mount"],
    description: "Professional Wi-Fi coverage for offices, schools, hotels and larger premises.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "hikvision-4-camera-cctv-kit",
    name: "Hikvision 4-Camera CCTV Kit with DVR",
    brand: "Hikvision",
    category: "cctv-security",
    price: 38500,
    oldPrice: 44000,
    sku: "AGK-SEC-001",
    condition: "Brand New",
    inStock: true,
    rating: 4.7,
    reviews: 19,
    tags: ["hot-deal", "featured", "best-seller"],
    specs: { Cameras: "4x 2MP HD", Recorder: "4-channel DVR", Storage: "1TB surveillance HDD", Viewing: "Mobile remote viewing" },
    features: ["Complete kit with cables and power supply", "Night vision cameras", "Watch live footage from your phone"],
    description:
      "A complete CCTV starter kit for homes, shops and small businesses. Professional installation available.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "dahua-8-channel-nvr",
    name: "Dahua 8-Channel NVR Recorder",
    brand: "Dahua",
    category: "cctv-security",
    price: 19500,
    sku: "AGK-SEC-002",
    condition: "Brand New",
    inStock: true,
    rating: 4.5,
    reviews: 6,
    tags: [],
    specs: { Channels: "8", Resolution: "Up to 4K", Storage: "Supports 1x HDD" },
    features: ["Records up to 8 IP cameras", "4K playback support", "Remote viewing app"],
    description: "An 8-channel network video recorder for growing IP camera installations.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "wd-purple-2tb-surveillance-drive",
    name: "WD Purple 2TB Surveillance Hard Drive",
    brand: "Western Digital",
    category: "cctv-security",
    price: 11500,
    sku: "AGK-SEC-003",
    condition: "Brand New",
    inStock: true,
    rating: 4.8,
    reviews: 10,
    tags: [],
    specs: { Capacity: "2TB", Type: "Surveillance-rated", Interface: "SATA" },
    features: ["Built for 24/7 recording", "Longer CCTV footage retention", "Low power, low heat"],
    description: "Surveillance-grade storage designed for continuous CCTV recording.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "agika-gaming-pc-rtx-3060",
    name: "AGIKA Custom Gaming PC — RTX 3060",
    brand: "AGIKA Build",
    category: "gaming",
    price: 165000,
    oldPrice: 179000,
    sku: "AGK-GAM-001",
    condition: "Brand New",
    inStock: true,
    rating: 4.9,
    reviews: 4,
    tags: ["featured", "new-arrival"],
    specs: {
      Processor: "Intel Core i5 12400F",
      RAM: "16GB DDR4",
      Storage: "1TB NVMe SSD",
      GPU: "NVIDIA RTX 3060 12GB",
      "Operating system": "Windows 11",
    },
    features: ["Assembled and tested in Nairobi", "Ready for 1080p/1440p gaming", "Upgrade-friendly build"],
    description: "A custom gaming desktop built by our technicians and tuned for smooth high-frame-rate gaming.",
    warranty: "12 months build warranty",
  }),
  p({
    slug: "24-inch-165hz-gaming-monitor",
    name: "24\" 165Hz Gaming Monitor",
    brand: "AOC",
    category: "gaming",
    price: 28900,
    sku: "AGK-GAM-002",
    condition: "Brand New",
    inStock: true,
    rating: 4.6,
    reviews: 9,
    tags: ["hot-deal"],
    specs: { "Screen size": "24 inch", "Refresh rate": "165Hz", "Response time": "1ms", Panel: "IPS" },
    features: ["Fast 165Hz refresh rate", "Adaptive sync support", "Slim bezel design"],
    description: "A fast gaming monitor for competitive play and smooth everyday visuals.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "rgb-mechanical-gaming-keyboard",
    name: "RGB Mechanical Gaming Keyboard",
    brand: "Redragon",
    category: "gaming",
    price: 5500,
    oldPrice: 6500,
    sku: "AGK-GAM-003",
    condition: "Brand New",
    inStock: true,
    rating: 4.5,
    reviews: 23,
    tags: ["clearance"],
    specs: { Switches: "Blue mechanical", Backlight: "RGB", Layout: "Full size" },
    features: ["Tactile mechanical switches", "Customisable RGB lighting", "Durable keycaps"],
    description: "A responsive mechanical keyboard for gaming, typing and long work sessions.",
    warranty: "6 months warranty",
  }),
  p({
    slug: "pos-thermal-receipt-printer-80mm",
    name: "80mm Thermal Receipt Printer",
    brand: "Xprinter",
    category: "pos-systems",
    price: 9500,
    sku: "AGK-POS-001",
    condition: "Brand New",
    inStock: true,
    rating: 4.6,
    reviews: 17,
    tags: ["best-seller"],
    specs: { "Paper width": "80mm", Speed: "250mm/s", Connectivity: "USB + LAN" },
    features: ["Fast, quiet receipt printing", "Auto paper cutter", "Works with most POS software"],
    description: "A workhorse receipt printer for shops, restaurants and retail counters.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "pos-barcode-scanner-wired",
    name: "Wired 1D Laser Barcode Scanner",
    brand: "Syble",
    category: "pos-systems",
    price: 4200,
    sku: "AGK-POS-002",
    condition: "Brand New",
    inStock: true,
    rating: 4.4,
    reviews: 11,
    tags: [],
    specs: { Type: "1D laser", Connectivity: "USB wired", Stand: "Included" },
    features: ["Fast, accurate scanning", "Plug-and-play USB", "Comes with desktop stand"],
    description: "A dependable barcode scanner for retail checkouts and stock control.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "all-in-one-pos-terminal",
    name: "All-in-One POS Terminal 15\" Touch",
    brand: "AGIKA Business",
    category: "pos-systems",
    price: 89000,
    sku: "AGK-POS-003",
    condition: "Brand New",
    inStock: true,
    rating: 4.7,
    reviews: 3,
    tags: ["featured"],
    specs: { Display: "15 inch touchscreen", Processor: "Intel Celeron", RAM: "8GB", Storage: "128GB SSD" },
    features: ["Complete counter solution", "Touch operation", "Setup and configuration available"],
    description: "A complete POS terminal for supermarkets, pharmacies, restaurants and retail shops.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "macbook-air-m1-13",
    name: "Apple MacBook Air M1 13\"",
    brand: "Apple",
    category: "apple",
    price: 128000,
    oldPrice: 139000,
    sku: "AGK-APL-001",
    condition: "Brand New",
    inStock: true,
    rating: 4.9,
    reviews: 13,
    tags: ["featured", "best-seller", "hot-deal"],
    specs: {
      Processor: "Apple M1",
      RAM: "8GB unified memory",
      Storage: "256GB SSD",
      "Screen size": "13.3 inch Retina",
      "Operating system": "macOS",
    },
    features: ["Exceptional battery life", "Silent fanless design", "Retina display"],
    description: "The M1 MacBook Air — light, fast and quiet, perfect for creators, students and professionals.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "macbook-pro-2019-core-i7",
    name: "Apple MacBook Pro 2019 Core i7 15\"",
    brand: "Apple",
    category: "apple",
    price: 145000,
    sku: "AGK-APL-002",
    condition: "Ex-UK / Refurbished",
    inStock: true,
    rating: 4.6,
    reviews: 5,
    tags: [],
    specs: {
      Processor: "Intel Core i7 9th Gen",
      RAM: "16GB",
      Storage: "512GB SSD",
      "Screen size": "15.4 inch Retina",
      "Operating system": "macOS",
    },
    features: ["Powerful creative workstation", "Bright Retina display", "Tested and certified"],
    description: "A capable Pro machine for video editing, design and heavy creative workloads.",
    warranty: "3 months limited warranty",
  }),
  p({
    slug: "apple-magic-mouse",
    name: "Apple Magic Mouse",
    brand: "Apple",
    category: "apple",
    price: 12500,
    sku: "AGK-APL-003",
    condition: "Brand New",
    inStock: true,
    rating: 4.4,
    reviews: 8,
    tags: [],
    specs: { Connectivity: "Bluetooth", Charging: "Rechargeable", Surface: "Multi-touch" },
    features: ["Seamless Mac pairing", "Multi-touch gestures", "Rechargeable battery"],
    description: "The official Apple Magic Mouse for a clean, gesture-driven Mac setup.",
    warranty: "12 months warranty",
  }),
  p({
    slug: "microsoft-office-2021-licence",
    name: "Microsoft Office 2021 Professional Licence",
    brand: "Microsoft",
    category: "software",
    price: 8500,
    oldPrice: 9500,
    sku: "AGK-SFT-001",
    condition: "Brand New",
    inStock: true,
    rating: 4.7,
    reviews: 25,
    tags: ["best-seller", "hot-deal"],
    specs: { Type: "Perpetual licence", Devices: "1 PC", Includes: "Word, Excel, PowerPoint, Outlook" },
    features: ["Genuine licence key", "Installation support available", "Delivered fast"],
    description: "A genuine Office licence for business and personal productivity, with installation help if needed.",
    warranty: "Licence support included",
  }),
  p({
    slug: "windows-11-pro-licence",
    name: "Windows 11 Pro Licence Key",
    brand: "Microsoft",
    category: "software",
    price: 6500,
    sku: "AGK-SFT-002",
    condition: "Brand New",
    inStock: true,
    rating: 4.6,
    reviews: 19,
    tags: [],
    specs: { Type: "Digital licence", Devices: "1 PC", Edition: "Pro" },
    features: ["Genuine activation key", "Pro security features", "Installation service available"],
    description: "Activate Windows 11 Pro with a genuine licence key, with optional installation service.",
    warranty: "Licence support included",
  }),
  p({
    slug: "kaspersky-antivirus-1-year",
    name: "Kaspersky Internet Security — 1 Year, 1 Device",
    brand: "Kaspersky",
    category: "software",
    price: 2500,
    sku: "AGK-SFT-003",
    condition: "Brand New",
    inStock: true,
    rating: 4.5,
    reviews: 14,
    tags: ["new-arrival"],
    specs: { Duration: "12 months", Devices: "1", Platform: "Windows" },
    features: ["Protects against malware and phishing", "Light on system resources", "Easy activation"],
    description: "Keep your computer protected with a genuine one-year antivirus licence.",
    warranty: "Licence support included",
  }),
];

export function getProduct(slug: string) {
  return products.find((prod) => prod.slug === slug);
}

export function productsByTag(tag: Product["tags"][number], limit?: number) {
  const list = products.filter((prod) => prod.tags.includes(tag));
  return typeof limit === "number" ? list.slice(0, limit) : list;
}

export function discountPercent(product: Product) {
  if (!product.oldPrice || product.oldPrice <= product.price) return 0;
  return Math.round(((product.oldPrice - product.price) / product.oldPrice) * 100);
}

const recommendationMap: Partial<Record<CategorySlug, CategorySlug[]>> = {
  computers: ["accessories", "software", "printers-scanners"],
  apple: ["accessories", "software"],
  "cctv-security": ["networking", "accessories"],
  networking: ["cctv-security", "accessories"],
  gaming: ["accessories", "networking"],
  "pos-systems": ["accessories", "networking"],
  "printers-scanners": ["accessories", "software"],
  software: ["computers", "accessories"],
  accessories: ["computers", "software"],
};

export function relatedProducts(product: Product, limit = 4) {
  const sameCategory = products.filter((x) => x.category === product.category && x.slug !== product.slug);
  const complements = (recommendationMap[product.category] ?? []).flatMap((cat) =>
    products.filter((x) => x.category === cat),
  );
  return [...sameCategory, ...complements].slice(0, limit);
}

export const brands = Array.from(new Set(products.map((x) => x.brand))).sort();
